---
services:
  runner:
    image: docker.io/gitea/act_runner:latest
    privileged: true
    restart: always
    deploy:
      replicas: 3
    environment:
      - GITEA_INSTANCE_URL=https://localhost:3000/
      - GITEA_RUNNER_REGISTRATION_TOKEN=xxxxxxxx
      - TZ=America/Chicago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
